#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_version.py — stamp source/version.h from git/CI metadata.

Version scheme (see VERSIONING.md):  v<upstream>-ko.<build>
  release:  "1.04-ko.2"           display "1.04ko2"
  dev:      "1.04-ko.dev+gabc1234" display "1.04ko-dev"

Resolution priority:
  1. $GITHUB_REF_NAME matching ^v(\\d+\\.\\d+)-ko\\.(\\d+)$  (tag builds)
  2. `git describe --tags --match 'v*-ko.*' --always`
       exact tag                         -> release
       v<up>-ko.<n>-<k>-g<sha>           -> dev on top of that tag
       bare sha (no tag yet)             -> dev with default upstream
  3. $GITHUB_SHA / nothing               -> dev placeholder

The display form must fit the 80px-wide help-screen slot: <= 10 chars
(enforced here).  Writing is idempotent: the file is only rewritten when
its content would change, so incremental builds are not invalidated.

Usage:
  python3 tools/gen_version.py            # write source/version.h
  python3 tools/gen_version.py --check    # print resolved version, no write
  python3 tools/gen_version.py -o PATH    # alternate output path
"""

import argparse
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT = os.path.join(REPO, "source", "version.h")

# Upstream EZ-FLASH Air kernel version this tree tracks (the in-kernel
# "K:1.04" display, helpwindow.c Show_ver). Bump when rebasing on a newer
# official kernel.
DEFAULT_UPSTREAM = "1.04"

TAG_RE = re.compile(r"^v(?P<up>\d+\.\d+)-ko\.(?P<n>\d+)$")
DESCRIBE_DEV_RE = re.compile(
    r"^v(?P<up>\d+\.\d+)-ko\.(?P<n>\d+)-\d+-g(?P<sha>[0-9a-f]+)$")
SHA_RE = re.compile(r"^[0-9a-f]{7,40}$")

MAX_DISPLAY = 10

TEMPLATE = """\
/* version.h — EZ-FLASH Air Korean kernel version macros.
 *
 * Regenerated by tools/gen_version.py (CI stamps release tags v<up>-ko.<n>
 * before building).  The committed default below is the dev placeholder —
 * do NOT hand-edit the values; see VERSIONING.md for the scheme.
 */
#ifndef KERNEL_KO_VERSION_H
#define KERNEL_KO_VERSION_H

/* full version string, e.g. "1.04-ko.2" or "1.04-ko.dev+gabc1234" */
#define KERNEL_KO_VERSION "%(version)s"

/* compact display form for the 80px-wide help-screen slot (<= 10 chars),
 * e.g. "1.04ko2" / "1.04ko-dev" */
#define KERNEL_KO_DISPLAY "%(display)s"

#endif /* KERNEL_KO_VERSION_H */
"""


def from_ref_name():
    """(upstream, build, sha) from a CI tag ref, or None."""
    m = TAG_RE.match(os.environ.get("GITHUB_REF_NAME", ""))
    if m:
        return m.group("up"), m.group("n"), None
    return None


def from_git_describe():
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--match", "v*-ko.*", "--always"],
            cwd=REPO, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None
    m = TAG_RE.match(out)
    if m:  # sitting exactly on a release tag
        return m.group("up"), m.group("n"), None
    m = DESCRIBE_DEV_RE.match(out)
    if m:  # commits on top of a release tag -> dev build of that upstream
        return m.group("up"), None, m.group("sha")[:7]
    if SHA_RE.match(out):  # no v*-ko.* tag anywhere yet
        return DEFAULT_UPSTREAM, None, out[:7]
    return None


def resolve():
    """Return (version, display)."""
    info = from_ref_name() or from_git_describe()
    if info is None:
        sha = os.environ.get("GITHUB_SHA", "")[:7]
        info = (DEFAULT_UPSTREAM, None, sha if SHA_RE.match(sha or "x" * 7) else None)
    up, build, sha = info
    if build is not None:
        version = "%s-ko.%s" % (up, build)
        display = "%sko%s" % (up, build)
    else:
        version = "%s-ko.dev" % up + ("+g%s" % sha if sha else "")
        display = "%sko-dev" % up
    if len(display) > MAX_DISPLAY:
        sys.stderr.write(
            "error: display version %r is %d chars; the help-screen slot "
            "fits %d. Shorten the build counter / upstream version.\n"
            % (display, len(display), MAX_DISPLAY))
        sys.exit(1)
    return version, display


def main():
    ap = argparse.ArgumentParser(description="stamp source/version.h")
    ap.add_argument("--check", action="store_true",
                    help="print the resolved version and exit (no write)")
    ap.add_argument("-o", "--output", default=DEFAULT_OUTPUT,
                    help="output header path (default: source/version.h)")
    args = ap.parse_args()

    version, display = resolve()

    if args.check:
        print(version)
        return 0

    content = TEMPLATE % {"version": version, "display": display}

    old = None
    if os.path.isfile(args.output):
        with open(args.output, "r", encoding="utf-8") as f:
            old = f.read()
    if old == content:
        print("version.h up to date: %s (display %s)" % (version, display))
        return 0

    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("wrote %s: %s (display %s)" % (args.output, version, display))
    return 0


if __name__ == "__main__":
    sys.exit(main())
