/* version.h — EZ-FLASH Air Korean kernel version macros.
 *
 * Regenerated by tools/gen_version.py (CI stamps release tags v<up>-ko.<n>
 * before building).  The committed default below is the dev placeholder —
 * do NOT hand-edit the values; see VERSIONING.md for the scheme.
 */
#ifndef KERNEL_KO_VERSION_H
#define KERNEL_KO_VERSION_H

/* full version string, e.g. "1.04-ko.2" or "1.04-ko.dev+gabc1234" */
#define KERNEL_KO_VERSION "1.04-ko.dev"

/* compact display form for the 80px-wide help-screen slot (<= 10 chars),
 * e.g. "1.04ko2" / "1.04ko-dev" */
#define KERNEL_KO_DISPLAY "1.04ko-dev"

#endif /* KERNEL_KO_VERSION_H */
